server:
    port: 8080
---
spring:
    cloud:
        gateway:
            discovery:
                locator:
                    enabled: true
            routes:
              - id: orders
                uri: lb://orders
                predicates:
                    - Path=/orders/**
                filters:
                    - RewritePath=/orders/(?<segment>.*), /$\{segment}
    application:
        name: gateway
---
management:
    endpoint:
        gateway:
            enabled: true
    endpoints:
        web:
            exposure:
                include: gateway
    